
spring:

 application:
  name: task-service

 cloud:
  consul:
   host: localhost
   port: 8500
   discovery:
    hostname: localhost
   config:
    enabled: true
    prefixes: configuration
    data-key: config-data
    default-context: application
    format: YAML


resilience4j:
  circuitbreaker:
    instances:
      emp-ms-cb:
       sliding-window-size: 6
       sliding-window-type: COUNT_BASED
       failure-rate-threshold: 50
       automatic-transition-from-open-to-half-open-enabled: true
       permitted-number-of-calls-in-half-open-state: 3
       wait-duration-in-open-state: 10000
       ignore-exceptions:
        - feign.FeignException$BadRequest
        - feign.FeignException$NotFound
        - com.taskmanager.task.exception.TaskManagerException









