server.port: 9000


resilience4j:
  circuitbreaker:
    instances:
      employee-circuit-breaker:
       slidingWindowSize: 6
       failureRateThreshold: 50
       waitDurationInOpenState: 10000



spring:
  application:
    name: gateway
  cloud:
   consul:
    host: localhost
    discovery:
     hostname: localhost
   
   gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: employee-service
         uri: lb://employee-service 
         predicates:
          - Path=/api/employee/**
         filters:
          - RewritePath=/api/(?<p>.*), /${p}
          - name: CircuitBreaker
            args:
             name: employee-circuit-breaker
             fallbackUri: forward:/fallback
         















