
spring:
  application:
    name: employee-service
  cloud:
   consul:
    host: localhost #where the consul server runs
    port: 8500
    discovery:
     hostname: localhost #where the app runs
    config:
      enabled: true
      prefixes: configuration
      default-context: application
      data-key: config-data
      format: YAML 